# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Chart_creator.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QLabel,
    QPlainTextEdit, QPushButton, QSizePolicy, QSpinBox,
    QTextEdit, QWidget)

class Ui_Chart_creator(object):
    def setupUi(self, Chart_creator):
        if not Chart_creator.objectName():
            Chart_creator.setObjectName(u"Chart_creator")
        Chart_creator.resize(940, 883)
        self.Edit_first_name = QTextEdit(Chart_creator)
        self.Edit_first_name.setObjectName(u"Edit_first_name")
        self.Edit_first_name.setGeometry(QRect(10, 80, 231, 21))
        self.Edit_last_name = QTextEdit(Chart_creator)
        self.Edit_last_name.setObjectName(u"Edit_last_name")
        self.Edit_last_name.setGeometry(QRect(10, 160, 231, 21))
        self.plainTextEdit = QPlainTextEdit(Chart_creator)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(570, 20, 51, 31))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit_2 = QPlainTextEdit(Chart_creator)
        self.plainTextEdit_2.setObjectName(u"plainTextEdit_2")
        self.plainTextEdit_2.setGeometry(QRect(10, 40, 81, 31))
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_3 = QPlainTextEdit(Chart_creator)
        self.plainTextEdit_3.setObjectName(u"plainTextEdit_3")
        self.plainTextEdit_3.setGeometry(QRect(10, 120, 81, 31))
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_4 = QPlainTextEdit(Chart_creator)
        self.plainTextEdit_4.setObjectName(u"plainTextEdit_4")
        self.plainTextEdit_4.setGeometry(QRect(10, 200, 121, 31))
        self.plainTextEdit_4.setReadOnly(True)
        self.Edit_Account_number = QTextEdit(Chart_creator)
        self.Edit_Account_number.setObjectName(u"Edit_Account_number")
        self.Edit_Account_number.setGeometry(QRect(10, 240, 231, 21))
        self.plainTextEdit_5 = QPlainTextEdit(Chart_creator)
        self.plainTextEdit_5.setObjectName(u"plainTextEdit_5")
        self.plainTextEdit_5.setGeometry(QRect(10, 280, 121, 31))
        self.plainTextEdit_5.setReadOnly(True)
        self.comboBox_1 = QComboBox(Chart_creator)
        self.comboBox_1.setObjectName(u"comboBox_1")
        self.comboBox_1.setGeometry(QRect(10, 320, 231, 26))
        self.spinBox_1 = QSpinBox(Chart_creator)
        self.spinBox_1.setObjectName(u"spinBox_1")
        self.spinBox_1.setGeometry(QRect(260, 320, 78, 26))
        self.spinBox_2 = QSpinBox(Chart_creator)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(260, 460, 78, 26))
        self.comboBox_2 = QComboBox(Chart_creator)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(10, 460, 231, 26))
        self.plainTextEdit_6 = QPlainTextEdit(Chart_creator)
        self.plainTextEdit_6.setObjectName(u"plainTextEdit_6")
        self.plainTextEdit_6.setGeometry(QRect(10, 420, 121, 31))
        self.plainTextEdit_6.setReadOnly(True)
        self.spinBox_3 = QSpinBox(Chart_creator)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setGeometry(QRect(260, 610, 78, 26))
        self.comboBox_3 = QComboBox(Chart_creator)
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(10, 610, 231, 26))
        self.plainTextEdit_7 = QPlainTextEdit(Chart_creator)
        self.plainTextEdit_7.setObjectName(u"plainTextEdit_7")
        self.plainTextEdit_7.setGeometry(QRect(10, 570, 121, 31))
        self.spinBox_4 = QSpinBox(Chart_creator)
        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setGeometry(QRect(260, 760, 78, 26))
        self.comboBox_4 = QComboBox(Chart_creator)
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(10, 760, 231, 26))
        self.plainTextEdit_8 = QPlainTextEdit(Chart_creator)
        self.plainTextEdit_8.setObjectName(u"plainTextEdit_8")
        self.plainTextEdit_8.setGeometry(QRect(10, 720, 121, 31))
        self.plainTextEdit_8.setReadOnly(True)
        self.plainTextEdit_10 = QPlainTextEdit(Chart_creator)
        self.plainTextEdit_10.setObjectName(u"plainTextEdit_10")
        self.plainTextEdit_10.setGeometry(QRect(580, 730, 121, 31))
        self.plainTextEdit_10.setReadOnly(True)
        self.comboBox_7 = QComboBox(Chart_creator)
        self.comboBox_7.setObjectName(u"comboBox_7")
        self.comboBox_7.setGeometry(QRect(580, 620, 231, 26))
        self.spinBox_7 = QSpinBox(Chart_creator)
        self.spinBox_7.setObjectName(u"spinBox_7")
        self.spinBox_7.setGeometry(QRect(830, 620, 78, 26))
        self.plainTextEdit_11 = QPlainTextEdit(Chart_creator)
        self.plainTextEdit_11.setObjectName(u"plainTextEdit_11")
        self.plainTextEdit_11.setGeometry(QRect(580, 430, 121, 31))
        self.plainTextEdit_11.setReadOnly(True)
        self.comboBox_6 = QComboBox(Chart_creator)
        self.comboBox_6.setObjectName(u"comboBox_6")
        self.comboBox_6.setGeometry(QRect(580, 470, 231, 26))
        self.plainTextEdit_12 = QPlainTextEdit(Chart_creator)
        self.plainTextEdit_12.setObjectName(u"plainTextEdit_12")
        self.plainTextEdit_12.setGeometry(QRect(580, 580, 121, 31))
        self.plainTextEdit_12.setReadOnly(True)
        self.spinBox_5 = QSpinBox(Chart_creator)
        self.spinBox_5.setObjectName(u"spinBox_5")
        self.spinBox_5.setGeometry(QRect(830, 330, 78, 26))
        self.spinBox_6 = QSpinBox(Chart_creator)
        self.spinBox_6.setObjectName(u"spinBox_6")
        self.spinBox_6.setGeometry(QRect(830, 470, 78, 26))
        self.comboBox_5 = QComboBox(Chart_creator)
        self.comboBox_5.setObjectName(u"comboBox_5")
        self.comboBox_5.setGeometry(QRect(580, 330, 231, 26))
        self.plainTextEdit_13 = QPlainTextEdit(Chart_creator)
        self.plainTextEdit_13.setObjectName(u"plainTextEdit_13")
        self.plainTextEdit_13.setGeometry(QRect(580, 290, 121, 31))
        self.plainTextEdit_13.setReadOnly(True)
        self.spinBox_8 = QSpinBox(Chart_creator)
        self.spinBox_8.setObjectName(u"spinBox_8")
        self.spinBox_8.setGeometry(QRect(830, 770, 78, 26))
        self.comboBox_8 = QComboBox(Chart_creator)
        self.comboBox_8.setObjectName(u"comboBox_8")
        self.comboBox_8.setGeometry(QRect(580, 770, 231, 26))
        self.Place_order = QPushButton(Chart_creator)
        self.Place_order.setObjectName(u"Place_order")
        self.Place_order.setGeometry(QRect(770, 120, 151, 61))
        self.Show_price = QPushButton(Chart_creator)
        self.Show_price.setObjectName(u"Show_price")
        self.Show_price.setGeometry(QRect(580, 120, 151, 61))
        self.Total_price = QLabel(Chart_creator)
        self.Total_price.setObjectName(u"Total_price")
        self.Total_price.setGeometry(QRect(590, 180, 271, 71))
        self.Exit_menu = QPushButton(Chart_creator)
        self.Exit_menu.setObjectName(u"Exit_menu")
        self.Exit_menu.setGeometry(QRect(780, 20, 151, 31))
        self.plainTextEdit_9 = QPlainTextEdit(Chart_creator)
        self.plainTextEdit_9.setObjectName(u"plainTextEdit_9")
        self.plainTextEdit_9.setGeometry(QRect(300, 160, 231, 31))
        self.plainTextEdit_9.setReadOnly(True)
        self.comboBox_11 = QComboBox(Chart_creator)
        self.comboBox_11.setObjectName(u"comboBox_11")
        self.comboBox_11.setGeometry(QRect(300, 190, 231, 26))

        self.retranslateUi(Chart_creator)

        QMetaObject.connectSlotsByName(Chart_creator)
    # setupUi

    def retranslateUi(self, Chart_creator):
        Chart_creator.setWindowTitle(QCoreApplication.translate("Chart_creator", u"Dialog", None))
        self.plainTextEdit.setPlainText(QCoreApplication.translate("Chart_creator", u"Chart", None))
        self.plainTextEdit_2.setPlainText(QCoreApplication.translate("Chart_creator", u"First name", None))
        self.plainTextEdit_3.setPlainText(QCoreApplication.translate("Chart_creator", u"Last Name", None))
        self.plainTextEdit_4.setPlainText(QCoreApplication.translate("Chart_creator", u"Account Number", None))
        self.plainTextEdit_5.setPlainText(QCoreApplication.translate("Chart_creator", u"Chose piece 1", None))
        self.plainTextEdit_6.setPlainText(QCoreApplication.translate("Chart_creator", u"Chose piece 2", None))
        self.plainTextEdit_7.setPlainText(QCoreApplication.translate("Chart_creator", u"Chose piece 3", None))
        self.plainTextEdit_8.setPlainText(QCoreApplication.translate("Chart_creator", u"Chose piece 4", None))
        self.plainTextEdit_10.setPlainText(QCoreApplication.translate("Chart_creator", u"Chose piece 8", None))
        self.plainTextEdit_11.setPlainText(QCoreApplication.translate("Chart_creator", u"Chose piece 6", None))
        self.plainTextEdit_12.setPlainText(QCoreApplication.translate("Chart_creator", u"Chose piece 7", None))
        self.plainTextEdit_13.setPlainText(QCoreApplication.translate("Chart_creator", u"Chose piece 5", None))
        self.Place_order.setText(QCoreApplication.translate("Chart_creator", u"Place my order", None))
        self.Show_price.setText(QCoreApplication.translate("Chart_creator", u"Show total price", None))
        self.Total_price.setText(QCoreApplication.translate("Chart_creator", u"Total price", None))
        self.Exit_menu.setText(QCoreApplication.translate("Chart_creator", u"Exit to main menu", None))
        self.plainTextEdit_9.setPlainText(QCoreApplication.translate("Chart_creator", u"Select starting time for the order", None))
    # retranslateUi

